[classroom]
# used by both teacher application and website
start_table = 1
end_table = 16
event_password = secret-password

# used only by teacher application
submit_to_server = false
server_url = http://localhost:5005/event
